"""Add MCP server models and relationships

Revision ID: b6814f5dcff8
Revises: 
Create Date: 2026-05-24 00:50:58.779790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6814f5dcff8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conn_metadata', sa.JSON(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connection_server_agent', 'mcp_connections', ['server_id', 'agent_id'], unique=False)
    op.create_index('idx_connection_status', 'mcp_connections', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_connections_agent_id'), 'mcp_connections', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mcp_connections_id'), 'mcp_connections', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_connections_server_id'), 'mcp_connections', ['server_id'], unique=False)
    op.create_table('mcp_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_server_name', 'mcp_prompts', ['server_id', 'name'], unique=False)
    op.create_index(op.f('ix_mcp_prompts_id'), 'mcp_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_prompts_name'), 'mcp_prompts', ['name'], unique=False)
    op.create_index(op.f('ix_mcp_prompts_server_id'), 'mcp_prompts', ['server_id'], unique=False)
    op.create_table('mcp_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('resource_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_server_uri', 'mcp_resources', ['server_id', 'uri'], unique=False)
    op.create_index(op.f('ix_mcp_resources_id'), 'mcp_resources', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_resources_server_id'), 'mcp_resources', ['server_id'], unique=False)
    op.create_index(op.f('ix_mcp_resources_uri'), 'mcp_resources', ['uri'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Enum('STDIO', 'SSE', 'HTTP', 'HTTPS', name='protocol_type'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN', 'DISCOVERING', name='server_status'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_check_interval', sa.Integer(), nullable=False),
    sa.Column('discovered_by', sa.String(length=50), nullable=True),
    sa.Column('discovery_metadata', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('server_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('auto_restart', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_created_at', 'mcp_servers', ['created_at'], unique=False)
    op.create_index('idx_server_protocol_status', 'mcp_servers', ['protocol', 'status'], unique=False)
    op.create_index('idx_server_status_active', 'mcp_servers', ['status', 'is_active'], unique=False)
    op.create_index(op.f('ix_mcp_servers_id'), 'mcp_servers', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=False)
    op.create_index(op.f('ix_mcp_servers_protocol'), 'mcp_servers', ['protocol'], unique=False)
    op.create_index(op.f('ix_mcp_servers_status'), 'mcp_servers', ['status'], unique=False)
    op.create_table('mcp_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_server_name', 'mcp_tools', ['server_id', 'name'], unique=False)
    op.create_index(op.f('ix_mcp_tools_id'), 'mcp_tools', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_tools_name'), 'mcp_tools', ['name'], unique=False)
    op.create_index(op.f('ix_mcp_tools_server_id'), 'mcp_tools', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_tools_server_id'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_name'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_id'), table_name='mcp_tools')
    op.drop_index('idx_tool_server_name', table_name='mcp_tools')
    op.drop_table('mcp_tools')
    op.drop_index(op.f('ix_mcp_servers_status'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_protocol'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_id'), table_name='mcp_servers')
    op.drop_index('idx_server_status_active', table_name='mcp_servers')
    op.drop_index('idx_server_protocol_status', table_name='mcp_servers')
    op.drop_index('idx_server_created_at', table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_mcp_resources_uri'), table_name='mcp_resources')
    op.drop_index(op.f('ix_mcp_resources_server_id'), table_name='mcp_resources')
    op.drop_index(op.f('ix_mcp_resources_id'), table_name='mcp_resources')
    op.drop_index('idx_resource_server_uri', table_name='mcp_resources')
    op.drop_table('mcp_resources')
    op.drop_index(op.f('ix_mcp_prompts_server_id'), table_name='mcp_prompts')
    op.drop_index(op.f('ix_mcp_prompts_name'), table_name='mcp_prompts')
    op.drop_index(op.f('ix_mcp_prompts_id'), table_name='mcp_prompts')
    op.drop_index('idx_prompt_server_name', table_name='mcp_prompts')
    op.drop_table('mcp_prompts')
    op.drop_index(op.f('ix_mcp_connections_server_id'), table_name='mcp_connections')
    op.drop_index(op.f('ix_mcp_connections_id'), table_name='mcp_connections')
    op.drop_index(op.f('ix_mcp_connections_agent_id'), table_name='mcp_connections')
    op.drop_index('idx_connection_status', table_name='mcp_connections')
    op.drop_index('idx_connection_server_agent', table_name='mcp_connections')
    op.drop_table('mcp_connections')
    # ### end Alembic commands ###
